logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: localhost # rabbitMQ的ip地址
    port: 5672 # 端口
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        prefetch: 1 # 消费端每次只预取一个消息,消费结束才取出下一个
        acknowledge-mode:  MANUAL # MANUAL
        retry:
          enabled: true #开启消费者失败重试
          stateless: false # true无状态   false 有状态。 如果业务中包含事务，这里改成false
          initial-interval: 1000 #初次失败重试等待时常
          multiplier: 1 # 失败的等待时长倍数,下次等待时常 = initial-interval * multiplier
          max-attempts: 3 #最大重试次数

#      direct:
#        refetch: 1
#        acknowledge-mode: NONE
